/** ExpressionType */
export enum ExpressionType {
    /** Add */
    Add = 0,
    /** AddChecked */
    AddChecked = 1,
    /** And */
    And = 2,
    /** AndAlso */
    AndAlso = 3,
    /** ArrayLength */
    ArrayLength = 4,
    /** ArrayIndex */
    ArrayIndex = 5,
    /** Call */
    Call = 6,
    /** Coalesce */
    Coalesce = 7,
    /** Conditional */
    Conditional = 8,
    /** Constant */
    Constant = 9,
    /** Convert */
    Convert = 10,
    /** ConvertChecked */
    ConvertChecked = 11,
    /** Divide */
    Divide = 12,
    /** Equal */
    Equal = 13,
    /** ExclusiveOr */
    ExclusiveOr = 14,
    /** GreaterThan */
    GreaterThan = 15,
    /** GreaterThanOrEqual */
    GreaterThanOrEqual = 16,
    /** Invoke */
    Invoke = 17,
    /** Lambda */
    Lambda = 18,
    /** LeftShift */
    LeftShift = 19,
    /** LessThan */
    LessThan = 20,
    /** LessThanOrEqual */
    LessThanOrEqual = 21,
    /** ListInit */
    ListInit = 22,
    /** MemberAccess */
    MemberAccess = 23,
    /** MemberInit */
    MemberInit = 24,
    /** Modulo */
    Modulo = 25,
    /** Multiply */
    Multiply = 26,
    /** MultiplyChecked */
    MultiplyChecked = 27,
    /** Negate */
    Negate = 28,
    /** UnaryPlus */
    UnaryPlus = 29,
    /** NegateChecked */
    NegateChecked = 30,
    /** New */
    New = 31,
    /** NewArrayInit */
    NewArrayInit = 32,
    /** NewArrayBounds */
    NewArrayBounds = 33,
    /** Not */
    Not = 34,
    /** NotEqual */
    NotEqual = 35,
    /** Or */
    Or = 36,
    /** OrElse */
    OrElse = 37,
    /** Parameter */
    Parameter = 38,
    /** Power */
    Power = 39,
    /** Quote */
    Quote = 40,
    /** RightShift */
    RightShift = 41,
    /** Subtract */
    Subtract = 42,
    /** SubtractChecked */
    SubtractChecked = 43,
    /** TypeAs */
    TypeAs = 44,
    /** TypeIs */
    TypeIs = 45,
    /** Assign */
    Assign = 46,
    /** Block */
    Block = 47,
    /** DebugInfo */
    DebugInfo = 48,
    /** Decrement */
    Decrement = 49,
    /** Dynamic */
    Dynamic = 50,
    /** Default */
    Default = 51,
    /** Extension */
    Extension = 52,
    /** Goto */
    Goto = 53,
    /** Increment */
    Increment = 54,
    /** Index */
    Index = 55,
    /** Label */
    Label = 56,
    /** RuntimeVariables */
    RuntimeVariables = 57,
    /** Loop */
    Loop = 58,
    /** Switch */
    Switch = 59,
    /** Throw */
    Throw = 60,
    /** Try */
    Try = 61,
    /** Unbox */
    Unbox = 62,
    /** AddAssign */
    AddAssign = 63,
    /** AndAssign */
    AndAssign = 64,
    /** DivideAssign */
    DivideAssign = 65,
    /** ExclusiveOrAssign */
    ExclusiveOrAssign = 66,
    /** LeftShiftAssign */
    LeftShiftAssign = 67,
    /** ModuloAssign */
    ModuloAssign = 68,
    /** MultiplyAssign */
    MultiplyAssign = 69,
    /** OrAssign */
    OrAssign = 70,
    /** PowerAssign */
    PowerAssign = 71,
    /** RightShiftAssign */
    RightShiftAssign = 72,
    /** SubtractAssign */
    SubtractAssign = 73,
    /** AddAssignChecked */
    AddAssignChecked = 74,
    /** MultiplyAssignChecked */
    MultiplyAssignChecked = 75,
    /** SubtractAssignChecked */
    SubtractAssignChecked = 76,
    /** PreIncrementAssign */
    PreIncrementAssign = 77,
    /** PreDecrementAssign */
    PreDecrementAssign = 78,
    /** PostIncrementAssign */
    PostIncrementAssign = 79,
    /** PostDecrementAssign */
    PostDecrementAssign = 80,
    /** TypeEqual */
    TypeEqual = 81,
    /** OnesComplement */
    OnesComplement = 82,
    /** IsTrue */
    IsTrue = 83,
    /** IsFalse */
    IsFalse = 84
}
