/** OpertionSymbol */
export enum OpertionSymbol {
    /** Equals */
    Equals = 0,
    /** NotEquals */
    NotEquals = 1,
    /** GreaterThan */
    GreaterThan = 2,
    /** NotGreaterThan */
    NotGreaterThan = 3,
    /** GreaterThanOrEqueals */
    GreaterThanOrEqueals = 4,
    /** LessThan */
    LessThan = 5,
    /** NotLessThan */
    NotLessThan = 6,
    /** LessThanOrEqual */
    LessThanOrEqual = 7,
    /** Like */
    Like = 8,
    /** NotLike */
    NotLike = 9,
    /** StartsWith */
    StartsWith = 10,
    /** NotStartsWith */
    NotStartsWith = 11,
    /** EndsWith */
    EndsWith = 12,
    /** NotEndsWith */
    NotEndsWith = 13,
    /** In */
    In = 14,
    /** NotIn */
    NotIn = 15,
    /** Between */
    Between = 16,
    /** NotBetween */
    NotBetween = 17,
    /** Fuzzy */
    Fuzzy = 18,
    /** NotFuzzy */
    NotFuzzy = 19
}
