/** OpertionSymbol */
export enum OpertionSymbol {
    /** None */
    None = 0,
    /** Equals */
    Equals = 1,
    /** NotEquals */
    NotEquals = 2,
    /** GreaterThan */
    GreaterThan = 3,
    /** NotGreaterThan */
    NotGreaterThan = 4,
    /** GreaterThanOrEqueals */
    GreaterThanOrEqueals = 5,
    /** LessThan */
    LessThan = 6,
    /** NotLessThan */
    NotLessThan = 7,
    /** LessThanOrEqual */
    LessThanOrEqual = 8,
    /** Like */
    Like = 9,
    /** NotLike */
    NotLike = 10,
    /** StartsWith */
    StartsWith = 11,
    /** NotStartsWith */
    NotStartsWith = 12,
    /** EndsWith */
    EndsWith = 13,
    /** NotEndsWith */
    NotEndsWith = 14,
    /** In */
    In = 15,
    /** NotIn */
    NotIn = 16,
    /** Between */
    Between = 17,
    /** NotBetween */
    NotBetween = 18,
    /** Fuzzy */
    Fuzzy = 19,
    /** NotFuzzy */
    NotFuzzy = 20,
    /** RegExp */
    RegExp = 21
}
